server:
  port: 8001
spring:
  elasticsearch:
    rest:
      #uris: http://192.168.16.16:9200
      uris: http://192.168.16.16:9200
  application:
    name: shop-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.16.16:8848
  rabbitmq:
    host: 192.168.16.16
    port: 5672
    username: admin
    password: 123
  redis:
    host: 192.168.16.16
    port: 6389
    database: 0
    timeout: 1800000
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 3000
        connectTimeout: 1000